# application.properties
spring.application.name=Lab2DecoratorSpring

# ?????? ??????????? ??? ?????? ???? (????? ???????)
# ????????? ????????: minVertex, throughVertices, weighted
use.decorators=minVertex

# ????????? ??? ?????????? throughVertices
required.vertices=C,E

# ????????? ??????
graph.start=B
graph.end=F

# ??? ?????????? ???????????:
# use.decorators=throughVertices,weighted
# use.decorators=weighted,throughVertices
