#Обязательные свойства
spring.application.name=CDISpringLAB6

#Выбор метода (должен соответствовать одному из бинов)
lcm.method = gcdBased

#Методы:
# gcdBased
# primeFactorization
# iterationBased

#Количество тестовых пар
test.pairs.count=5

#Настройки логирования
logging.level.root=INFO
logging.level.ru.rut_miit.lab1cdispring=DEBUG

#Отключаем баннер
spring.main.banner-mode=off
